# GPT Model output:

# Response(id='resp_072a46a7a81ef9060069c5c8f1be8c8193a674ffd47278ea99', created_at=1774569713.0, error=None, 
#          incomplete_details=None, instructions=None, metadata={}, model='gpt-4o-mini-2024-07-18', object='response', 
#          output=[ResponseFunctionToolCall(arguments='{"lat":25.7617,"long":-80.1918}', call_id='call_SEJMUA7UF6lQbNGI7ZTIQ3uB', name='get_weather', type='function_call', id='fc_072a46a7a81ef9060069c5c8f2858081939e733d59967ebe58', namespace=None, status='completed')], 
#          parallel_tool_calls=True, temperature=0.6, tool_choice='auto', 
#          tools=[FunctionTool(name='get_weather', parameters={'type': 'object', 'properties': {'lat': {'type': 'number', 'description': 'Latitude of the location'}, 'long': {'type': 'number', 'description': 'Longitude of the location'}}, 'required': ['lat', 'long'], 'additionalProperties': False}, strict=True, type='function', defer_loading=None, description='Get the current weather for a given location')], 
#          top_p=1.0, background=False, 
#          completed_at=1774569714.0, 
#          conversation=None, 
#          max_output_tokens=4000, 
#          max_tool_calls=3, 
#          previous_response_id=None, 
#          prompt=None, 
#          prompt_cache_key=None, 
#          prompt_cache_retention=None, 
#          reasoning=Reasoning(effort=None, generate_summary=None, summary=None), 
#          safety_identifier=None, service_tier='default', status='completed', 
#          text=ResponseTextConfig(format=ResponseFormatText(type='text'), verbosity='medium'), top_logprobs=0, truncation='disabled', 
#          usage=ResponseUsage(input_tokens=62, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=26, 
#                              output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=88), 
#                              user=None, billing={'payer': 'developer'}, frequency_penalty=0.0, presence_penalty=0.0, store=True)

# ParsedResponse[~TextFormatT](id='resp_0729263a88e7065c0069c5cad5431c8196ab61e1fb8080f3d4', created_at=1774570197.0, error=None, 
#                              incomplete_details=None, instructions=None, metadata={}, model='gpt-4o-mini-2024-07-18', object='response', 
#                              output=[ParsedResponseOutputMessage[~TextFormatT](id='msg_0729263a88e7065c0069c5cad5e84c81968cc057f593a2f3cb', content=[ParsedResponseOutputText[~TextFormatT](annotations=[], text='{"city":"Miami"}', type='output_text', logprobs=[], parsed=city(city='Miami'))], role='assistant', status='completed', type='message', phase=None)],
#                                parallel_tool_calls=True, temperature=0.6, tool_choice='auto', tools=[], top_p=1.0, background=False, 
#                                completed_at=1774570197.0, conversation=None, max_output_tokens=4000, max_tool_calls=3, 
#                                previous_response_id=None, prompt=None, prompt_cache_key=None, prompt_cache_retention=None, 
#                                reasoning=Reasoning(effort=None, generate_summary=None, summary=None), safety_identifier=None, 
#                                service_tier='default', status='completed', 
#                                text=ResponseTextConfig(format=ResponseFormatTextJSONSchemaConfig(name='city', schema_={'properties': {'city': {'title': 'City', 'type': 'string'}}, 'required': ['city'], 'title': 'city', 'type': 'object', 'additionalProperties': False}, type='json_schema', description=None, strict=True), verbosity='medium'), 
#                                top_logprobs=0, truncation='disabled', usage=ResponseUsage(input_tokens=44, 
#                                input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=6, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=50), 
#                                user=None, billing={'payer': 'developer'}, frequency_penalty=0.0, presence_penalty=0.0, store=True)

# (Response(id='resp_049fef44596568fa0069c72235885881938aad69dbd72b6d09', created_at=1774658101.0, error=None, 
#           incomplete_details=None, instructions=None, metadata={}, model='gpt-4o-mini-2024-07-18', object='response', 
#           output=[ResponseOutputMessage(id='msg_049fef44596568fa0069c722364f048193911c971978fa0623', content=[ResponseOutputText(annotations=[], text='The capital of France is Paris.', type='output_text', logprobs=[])], role='assistant', status='completed', type='message', phase=None)],
#             parallel_tool_calls=True, temperature=0.6, tool_choice='auto', tools=[], top_p=1.0, background=False, 
#             completed_at=1774658102.0, conversation=None, max_output_tokens=4000, max_tool_calls=None, previous_response_id=None, prompt=None, prompt_cache_key=None, prompt_cache_retention=None, 
#             reasoning=Reasoning(effort=None, generate_summary=None, summary=None), safety_identifier=None, service_tier='default', status='completed', 
#             text=ResponseTextConfig(format=ResponseFormatText(type='text'), verbosity='medium'), top_logprobs=0, truncation='disabled', 
#             usage=ResponseUsage(input_tokens=14, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=8, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=22), 
#             user=None, billing={'payer': 'developer'}, frequency_penalty=0.0, presence_penalty=0.0, store=True),
#  None)