from pydantic import BaseModel, Field,ConfigDict,model_validator
from typing import List, Optional, Dict, Any



#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Coder Structured Output Schema
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

class CoderOutput(BaseModel):
    """
    CoderOutput defines the structured output format for the Coder agent. 
    """
    model_config = ConfigDict(extra="forbid")
    
    thought_process: str = Field(
        ..., 
        description="The Coder Agent's internal reasoning and thought process leading to the code solution. This should be a detailed explanation of how the agent is interpreting the user's request and the dataset context."
    )
    
    #Flattening these out removes the need for a dynamic dictionary entirely
    language: str = Field(
        default=None,
        description="The programming language used in the code snippet (e.g., Python, SQL)."
    )
    
    
    executable_code: str= Field(
        default=None,
        description="The code snippet generated by the Coder Agent in response to the user's query. This should be executable code that directly addresses the user's request based on the dataset context and any instructions provided by the Supervisor Agent."
    )

    results_interpretation: str = Field(
        default=None,
        description="The results and interpretation from executing the code."
    )

    error: Optional[str] = Field(
        default=None,
        description="If the Coder Agent encountered any issues while generating the code, this field should contain a description of the error. If no errors were encountered, this field should be null."
    )